### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by AdamYLiang** [saphknight/SlackClone-Name-Pending#1]
**Users Table**
- [x] Should have a column for profile/user image

**Channels Table**
- [x] Should have a column for a description
- [x] `workspace_id` should be a foreign key

**Messages Table**
- [x] Combine `messages` into one table 
- [x] `channel_id` and `user_id` should be foreign keys
I agree that `messages` and `direct_messages` can be combined into just `messages`. In that case it would be fine to add a `dm` flag in the channel. 

**Users-Workspaces Joins Table**
- [x] `user_id` and `workspace_id` should be foreign keys

If you redo the DMs to have channels keep track of it, you wouldn't need a DM joins table. 

Let me know if you have any questions or want to talk about these!

**Comment by saphknight** [comment]
* Added column for `user_image_url` in `users`
* Added column for `description` in `channels`
* Added `foreign key` tag for `workspace_id` in `channels`
* Merged `direct_messages` and `channels` into `channels`, added a `dm?` `boolean` column in `channels`
* Added `foreign key` tag for `channel_id` and `user_id` in `messages`
* Added `foreign key` tag for `user_id` and `workspace_id` in the `users_workspaces` joins table
* Changed `user_dms` joins table to `user_channels` joins table

Now that DM's and Channels are one table, I will need a users to channels joins table to keep track of which users will have access to which channels. For regular channels, all users in the workspace will have access and for DM's, only specific users will have access. This joins table will track this.

**Comment by AdamYLiang** [comment]
Changes look good to me, nice work!
