### ISSUE TITLE
Frontend/Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [saphknight/SlackClone-Name-Pending#3]
### Frontend Routes
- [x] Should have a route for `/get_started`
- [x] Nest channels/DMs under `/messages`. (Check Slack website to see how the URL changes)

### Backend Routes
**Users**
- [x] Should have a `GET` for all users

**Workspaces**
- [x] Should have a `PATCH` to update 

**Messages**
- [x] Might not need `GET` for individual message should be nested under channels as well

Let me know if you have any questions or want to talk about any of these!

**Comment by saphknight** [comment]
* Added a route for `/get_started`
* Nested channels/DMs under `/messages`
* Added a `GET` for all users 
* Added a `PATCH` for workspaces 
* Removed `GET` for individual messages
