### ISSUE TITLE
Frontend Auth

### ISSUE THREAD

**Issue by saphknight** [saphknight/SlackClone-Name-Pending#4]
- [ ] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for user
- [x] MVP allows for a demo user login 
- [x] MVP passes email info from splash page to signup page
- [x] MVP shows animation of images cycled in an array

**Comment by AdamYLiang** [comment]
- [ ] Logging out should prompt us to `sign back in` page
- [ ] No dead buttons on nav bar 
- [ ] Consider adding a footer to splash page with links to your Github and LinkedIn
